### ISSUE TITLE
Peabody, Public and Local - AAPB Review

### ISSUE THREAD

**Issue by ekemeyer** [WGBH-MLA/mla-tickets#101]
# Details 
I need help reviewing the Peabody, Public and Local inventory for any items that we already have in the AAPB. I have pulled any items not being considered for digitization. Please ignore any color-coding or notes. If you could ID any definite or possible matches with what we have in the AAPB, I will then go in and do a manual review of any possible matches. 

Here is the link to the spreadsheet to be reviewed: https://docs.google.com/spreadsheets/d/1ohp7p9AFAQvbwQaRVcYcTuP_rfi7yENq/edit?usp=drive_link&ouid=108149403695409322580&rtpof=true&sd=true 

Please let me know if you have any questions! Thanks - Michelle

Submitted by: Michelle
CC in communications: 
Priority: Medium (within this month)
URL: https://docs.google.com/spreadsheets/d/1ohp7p9AFAQvbwQaRVcYcTuP_rfi7yENq/edit?usp=drive_link&ouid=108149403695409322580&rtpof=true&sd=true 
Slack message thread:

**Comment by ekemeyer** [comment]
duplicate

**Comment by ekemeyer** [comment]
Not a duplicate!

**Comment by foo4thought** [comment]
[combos_updated_removed.xlsx.gz](https://github.com/user-attachments/files/17683621/combos_updated_removed.xlsx.gz)
as done for #93 , applescript brokered data from XSLX to TSV and then BASH scripts performed lookups on AAPB, writing to JSON files in hierarchical directory structure (top-level directory == line number of spreadsheet), then more BASH scripts parsing JSON in file system locations to TSV which is imported back to XLSX and then enhanced with some more applescript (word-level metrics between titles of Peabody and AAPB) and into Excel for tricks to enhance/filter data for the operator. 
[report_ssline_barcode_vertitle_aapbtitle_guid_corrected.tsv.txt](https://github.com/user-attachments/files/17683696/report_ssline_barcode_vertitle_aapbtitle_guid_corrected.tsv.txt)
[Terminal Saved Output.txt](https://github.com/user-attachments/files/17683699/Terminal.Saved.Output.txt)
[Terminal Saved Output2.txt](https://github.com/user-attachments/files/17683700/Terminal.Saved.Output2.txt)
[Terminal Saved Output3.txt](https://github.com/user-attachments/files/17683701/Terminal.Saved.Output3.txt)
[Terminal Saved Output4.txt](https://github.com/user-attachments/files/17683702/Terminal.Saved.Output4.txt)
