### ISSUE TITLE
WRVR Whisper History

### ISSUE THREAD

**Issue by ekemeyer** [WGBH-MLA/mla-tickets#103]
### Because

I am working on shutting down our WRVR Fixit+ site and want to push all guids to AAPB but do not want to write over any recent whisper transcripts that might be better than the unedited guids in Fixit+ that were generated by Kaldi.

Is it possible to know if the attached list of guids have been run through whisper? And if so, when?
[wrvr_fixit+.txt](https://github.com/user-attachments/files/17527024/wrvr_fixit%2B.txt)

### Done when

I know if these were whispered and if so, when.

**Comment by foo4thought** [comment]
[whisper_output_github103.txt](https://github.com/user-attachments/files/17559627/whisper_output_github103.txt)
tab-delimited lines (UNIX) of GUID and whisper-related s3 metadata ( key | size | last_modified ) 
Beware 3 items that output zero-byte transcripts:

1. line 96: cpb-aacip-528-rn3028qt1c	s3://asr-dockerwhisper-output/cpb-aacip-528-rn3028qt1c/cpb-aacip-528-rn3028qt1c-transcript.json | 0 | 2023-11-17T23:05:06+00:00
2. line 108: cpb-aacip-528-pk06w97m9g	s3://asr-dockerwhisper-output/cpb-aacip-528-pk06w97m9g/cpb-aacip-528-pk06w97m9g-transcript.json | 0 | 2023-11-16T02:12:10+00:00
3. line 128: cpb-aacip-528-n00zp3x612	s3://asr-dockerwhisper-output/cpb-aacip-528-n00zp3x612/cpb-aacip-528-n00zp3x612-transcript.json | 0 | 2024-01-30T09:54:41+00:00
