### ISSUE TITLE
guids and metadata

### ISSUE THREAD

**Issue by ekemeyer** [WGBH-MLA/mla-tickets#108]
# Details 
I'm trying to retrieve the guids for file renaming for a set of NJN local ids. But i'm unsure who to contact about this now that the workflow no longer has to be routed through AMS1 or presumably requires me to redo all the metadata. 

Submitted by: Raananah Sarid-Segal
CC in communications: 
Priority: High (within the week)
URL: 
Slack message thread:

**Comment by ekemeyer** [comment]
[njn_local_ids.xlsx](https://github.com/user-attachments/files/17648778/njn_local_ids.xlsx)

**Comment by ekemeyer** [comment]
@foo4thought can you take on this request and provide gory details? I'm curious about the best way to do this without having to pull down all 82K records in New Jersey Network!

**Comment by foo4thought** [comment]
[mysql_output.txt](https://github.com/user-attachments/files/17663179/mysql_output.txt)
[PASTEBOARD_CONTENTS.txt](https://github.com/user-attachments/files/17663323/PASTEBOARD_CONTENTS.txt)


`# collect data from excel and reformat to get rid of those pesky preambles of zeroes
mylocal:mysql_docker_ams kevin_carter$ osascript <<EOF
 set AppleScript's text item delimiters to "\",\""
tell application "Microsoft Excel" to string value of range "[njn_local_ids.xlsx]Sheet1!B2:C348"
{result, {}}
repeat with rowData in item 1 of result
        repeat with colData in contents of rowData
                {{}, item 2 of result & (do shell script "echo " & quoted form of colData & " | sed 's#^0*##1'")}
        end repeat
end repeat
"(\"" & (item 2 of result as string) & "\")"
set the clipboard to result
 EOF
mylocal:mysql_docker_ams kevin_carter$ # USE THE PASTEBOARD CONTENTS IN THE SELECT STATEMENT BELOW
mylocal:mysql_docker_ams kevin_carter$ docker run --hostname=9a8b8b55c5c6 --mac-address=02:42:ac:11:00:03 --env=MYSQL_ROOT_PASSWORD="$p" --env=MYSQL_DATABASE=ams --env=MYSQL_USER=ams --env=PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin --env=GOSU_VERSION=1.17 --env=MYSQL_MAJOR=8.0 --env=MYSQL_VERSION=8.0.39-1.el9 --env=MYSQL_SHELL_VERSION=8.0.38-1.el9 --volume=/Users/kevin_carter/Downloads/mysql_docker_ams/data:/var/lib/mysql --volume=/Users/kevin_carter/Downloads/mysql_docker_ams/dump:/docker-entrypoint-initdb.d --volume=/var/lib/mysql -v /tmp/:/hosttmp/ --network=bridge --restart=no --runtime=runc -d arm64v8/mysql:8.0
mylocal:mysql_docker_ams kevin_carter$ docker ps
CONTAINER ID   IMAGE                                       COMMAND                  CREATED          STATUS                PORTS                 NAMES
ad44db463514   arm64v8/mysql:8.0                           "docker-entrypoint.s…"   11 minutes ago   Up 11 minutes         3306/tcp, 33060/tcp   modest_yalow
64c30eb5a7c1   ghcr.io/wgbh-mla/whisper-bot:arm64-v0.2.0   "whisper --language …"   3 hours ago      Up 3 hours (Paused)                         1730980556
mylocal:mysql_docker_ams kevin_carter$ docker exec -it ad44db463514 /bin/bash
bash-5.1#

bash-5.1# mysql ams -u root -p
Enter password: 
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 17
Server version: 8.0.39 MySQL Community Server - GPL

Copyright (c) 2000, 2024, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> select id,station_name from stations where station_name like "New Jersey%";
+-----+--------------------+
| id  | station_name       |
+-----+--------------------+
| 122 | New Jersey Network |
+-----+--------------------+
1 row in set (0.01 sec)



mysql> exit;
Bye

bash-5.1# echo 'select guid.identifier, local.identifier from assets inner join identifiers as guid on guid.assets_id = assets.id and guid.identifier_source="http://americanarchiveinventory.org" inner join identifiers as local on guid.assets_id = local.assets_id   where stations_id=122 and local.identifier in ("5889","11-5889","77314","BS-624","78287","BT-11364","80159","BT-6407","81420","BT-8804","8297","6-8297","77320","BS-581","78288","BT-11365","80339","BT-2378","81421","BT-8805","10144","11-10144","77326","BS-529","78289","BT-11366","80345","BT-2387","81424","BT-8808","25300","5-25300","77327","BS-528","78290","BT-11367","80348","BT-2395","81431","BT-8835","29332","2-29332","77328","BS-521","78295","BT-11377","80349","BT-2396","81435","BT-8839","29364","2-29364","77343","BS-3292","78296","BT-11378","80352","BT-2406","81437","BT-8842","29799","11-29799","77348","BS-805","78297","BT-11379","80354","BT-2409","81447","BT-8860","29801","11-29801","77350","BS-785","78298","BT-11380","80361","BT-2433","81448","BT-8861","29806","11-29806","77354","BS-751","78300","BT-11382","80362","BT-2437","81451","BT-8864","31311","10-31311","77359","BS-733","78301","BT-11383","80364","BT-2447","81471","BT-5675","32670","2-32670","77390","BS-1202","78304","BT-11386","80365","BT-2451","81475","BT-5694","39337","4-39337","77394","S-1140","78307","BT-11391","80366","BT-2454","81480","BT-5742","39341","4-39341","77395","BS-1144","78310","BT-11394","80367","BT-2457","81545","BT-5225","49649","12-49649","77407","S-1069","78311","BT-11396","80370","BT-2466","81546","BT-5231","49650","12-49650","77409","BS-1057","78312","BT-11397","80372","BT-2476","81571","BT-5072","49652","12-49652","77424","BS-1350","78313","BT-11399","80375","BT-2480","81572","BT-5073","49654","12-49654","77427","BS-1320","78314","BT-11400","80379","BT-2505","81576","BT-5105","49655","4-49655","77429","BS-1297","78319","BT-11407","80386","BT-2517","81585","BT-5161","49656","4-49656","77431","BS-1305","78320","BT-11408","80388","BT-2533","81589","BT-5178","49659","4-49659","77435","BS-1268","78321","BT-11417","80407","BT-2611","81592","BT-5191","49665","4-49665","77484","BT-12235","78326","BT-11429","80416","BT-2687","81598","BT-4936","49670","4-49670","77508","BT-12408","78327","BT-11430","80485","BT-2990","81608","BT-4979","49671","4-49671","77510","BT-12402","78328","BT-11434","80504","BT-3051","81610","BT-4995","49673","4-49673","77515","BT-12381","78329","BT-11435","80506","BT-3053","81612","BT-5003","49679","4-49679","77516","BT-12380","78330","BT-11436","80507","BT-3056","82097","BT-989","51303","2-51303","77528","BT-12292","78331","BT-11448","80515","BT-3083","82428","BT-9244","51604","2-51604","77531","BT-12639","78340","BT-12856","80522","BT-3105","82432","BT-9249","51605","2-51605","77599","BT-12071","78506","BT-14103","80527","BT-3114","82440","BT-9292","51613","2-51613","77904","BT-13744","78626","BT-15019","80528","BT-3121","82441","BT-9293","51629","2-51629","78010","BT-13936","79235","BT-11640","80532","BT-3139","82450","BT-9384","51631","2-51631","78033","BT-13972","79237","BT-11642","81237","BT-9762","82458","BT-9438","51641","2-51641","78063","BT-13985","79239","BT-11644","81238","BT-9763","82465","BT-9471","66895","2-66895","78089","BT-14055","79241","BT-11647","81239","BT-9764","82467","BT-9473","68599","5-68599","78093","BT-14059","79243","BT-11646","81240","BT-9765","82468","BT-9474","76510","BS-3766","78097","BT-14063","79246","BT-11653","81242","BT-9768","82481","BT-9540","76564","BS-4215","78107","BT-7615","79247","BT-11654","81243","BT-9769","82487","BT-9546","76716","R-18970","78221","BT-11705","79248","BT-11655","81244","BT-9770","82515","BT-9607","76717","7-76717","78222","BT-11706","79250","BT-11657","81245","BT-9771","82516","BT-9608","76757","BS-3281","78224","BT-11711","79255","BT-11663","81246","BT-9772","82519","BT-9611","76807","BS-3075","78227","BT-11714","79256","BT-11664","81247","BT-9773","82522","BT-9614","76815","BS-3084","78229","BT-11717","79257","BT-11665","81248","BT-9774","82525","BT-9617","76818","BS-3091","78230","BT-11718","79258","BT-11666","81249","BT-9775","82528","BT-9620","76820","BS-3095","78232","BT-11723","79260","BT-11668","81250","BT-9776","82550","BT-7114","76848","BS-3034","78233","BT-11724","79262","BT-11671","81253","BT-9779","82555","BT-7094","76851","BS-3031","78234","BT-11725","79264","BT-11673","81255","BT-9781","82556","BT-7090","76856","BS-3024","78235","BT-11726","79265","BT-11678","81256","BT-9782","82557","BT-7088","76907","BS-2965","78236","BT-11730","79266","BT-11679","81258","BT-9784","82565","BT-7067","76955","BS-2874","78237","BT-11732","79267","BT-11680","81259","BT-9785","82574","BT-7037","76957","BS-2876","78238","BT-11743","79268","BT-11681","81260","BT-9786","82578","BT-7017","76962","BS-2882","78242","BT-11296","79269","BT-11684","81262","BT-9788","82587","BT-6955","76964","BS-2639","78246","BT-11310","79270","BT-11694","81264","BT-9790","82588","BT-6947","76965","BS-2640","78247","BT-11311","79272","BT-11697","81265","BT-9791","82600","BT-6878","76970","BS-2675","78250","BT-11314","79278","BT-11516","81267","BT-9793","82613","BT-6795","76986","BS-2797","78251","BT-11315","79280","BT-11518","81270","BT-9796","82640","BT-6650","77031","BS-2536","78252","BT-11316","79281","BT-11519","81271","BT-9797","82667","BT-6470","77228","BS-12","78257","BT-11323","79284","BT-11061","81272","BT-9798","82673","BT-6513","77233","BS-21","78259","BT-11325","79285","BT-11062","81273","BT-9799","83978","BN-866","77266","BS-216","78261","BT-11327","79286","BT-11065","81274","BT-9800","83979","BN-868","77268","BS-220","78265","BT-11332","79287","BT-11066","81275","BT-9801","83982","BN-883","77269","BS-223","78266","BT-11333","79288","BT-11067","81280","BT-9807","83983","BN-884","77280","BS-301","78267","BT-11334","79290","BT-11069","81281","BT-9808","83993","BN-909","77282","BS-344","78270","BT-11340","79310","BT-11093","81282","BT-9809","83994","BN910","77283","BS-346","78271","BT-11342","79321","BT-11107","81283","BT-9810","83995","BN-911","77286","BS-353","78272","BT-11343","79322","BT-11108","81285","BT-9812","84411","H30-1230","77290","BS-370","78276","BT-11348","79323","BT-11109","81288","BT-9816","84412","H30-1229","77294","BS-388","78278","BT-11351","79324","BT-11110","81393","BT-8777","84413","H30-1224","77296","BS-403","78280","BT-11353","79325","BT-11111","81402","BT-8523","84416","H30-1219","77301","BS-446","78281","BT-11354","79326","BT-11112","81407","BT-8791","77311","BS-634","78283","BT-11360","80144","BT-6373","81408","BT-8792","77313","BS-630","78284","BT-11361","80154","BT-6397","81409","BT-8793");' | mysql ams -u root -p > /hosttmp/mysql_output.txt
bash-5.1# head /hosttmp/mysql_output.txt 
identifier	identifier
cpb-aacip/259-696zzs6b	10-31311
cpb-aacip/259-0863741v	10144
cpb-aacip/259-0863741v	11-10144
cpb-aacip/259-348ghd3x	11-29799
cpb-aacip/259-901zgx6q	11-29801
cpb-aacip/259-8k74x662	11-29806
cpb-aacip/259-736m2p18	11-5889
cpb-aacip/259-hh6c544b	12-49649
cpb-aacip/259-bz618g1j	12-49650
bash-5.1# 
bash-5.1# exit
mylocal:mysql_docker_ams kevin_carter$ docker stop ad44db463514 && docker rm ad44db463514
ad44db463514
ad44db463514
mylocal:mysql_docker_ams kevin_carter$
`
