### ISSUE TITLE
ams2 QA report:  count instantiations 

### ISSUE THREAD

**Issue by ekemeyer** [WGBH-MLA/mla-tickets#118]
# Details 
for each GUID on OV_GUID_check_list.txt, count and report the number of instantiations in AMS2

Submitted by: Peter Higgins
CC in communications: 
Priority: Medium (within this month)
URL: 
Slack message thread: https://wgbh.slack.com/archives/DLXCH9HBL/p1732202493066499

**Comment by foo4thought** [comment]
`mylocal:OV_GUID_check_list kevin_carter$ read -p 'enter your ams2 password:  ' p
enter your ams2 password:  •••••••••••

mylocal:OV_GUID_check_list kevin_carter$ for guid in $(cat OV_GUID_check_list.txt );do echo "$(echo $guid;curl -sS -u kevin_carter@wgbh.org:$p https://ams2.wgbh-mla.org/concern/asset_resources/"$guid".xml | xpath -e 'count(//pbcoreInstantiation)' 2>/dev/null)" | paste - - | tee -a guid_count-instantiations.tsv;done

mylocal:OV_GUID_check_list kevin_carter$ for guid in $(grep '\t0$' guid_count-instantiations.tsv | cut -f1);do echo "$(echo $guid;curl -sS -I -u kevin_carter@wgbh.org:$p https://ams2.wgbh-mla.org/concern/asset_resources/"$guid".xml | head -1 | awk '{print $2}')" | paste - -  | tee -a guid-zero_http-code.tsv ;done`
[guid-zero_http-code.tsv.gz](https://github.com/user-attachments/files/17875338/guid-zero_http-code.tsv.gz)
[guid_count-instantiations.tsv.gz](https://github.com/user-attachments/files/17875339/guid_count-instantiations.tsv.gz)
