### ISSUE TITLE
OCLC report for Unique GUIDS only

### ISSUE THREAD

**Issue by ekemeyer** [WGBH-MLA/mla-tickets#121]
### Because

The latest outputs for sending into OCLC/world cat look great - however, I learned that we should only be sending in what has been added to AAPB recently, so as to not duplicate records in their catalog.

Can you take both the recent xml outputs and extract only the unique guid records? 

I've done the work of identifying what is unique (~20K).
[unique_guids.txt](https://github.com/user-attachments/files/18012514/unique_guids.txt)

### Done when

XML for OCLC only includes records that we have yet to send into their catalog.

### Additional context

I've already looked at what we put into OCLC in the last transfer and identified what is unique in the new transfer. List of guids are in this ticket.

**Comment by foo4thought** [comment]
reworking the lists of GUIDs but when it's done, here's the code to fetch the JSON:
```
mylocal:oclc_20241204 kevin_carter$ for i in $(seq 50 50 $(wc -l unique_guids_clean.txt | awk '{print $1}') );\
do q=$( head -$i unique_guids_clean.txt | tail -50 | sed 's#\(.\{9\}\).#\1?#1;s#^#%20%20OR%20id:#1' | tr -d '\n' | cut -c12-) ;\
curl -sS "https://americanarchive.org/api.json?fl=id,xml&rows=50&start=0&q=$q" > $i.json  ;\
done
```

**Comment by foo4thought** [comment]
here are GUIDs (modified to conform to dash standard) collected on 20241107 that were NOT collected 20240815
[guids_not_oclc20240815.txt](https://github.com/user-attachments/files/18023862/guids_not_oclc20240815.txt)

**Comment by foo4thought** [comment]
instead of using GUIDs to extract from already-generated XML, I propose to use the GUIDs to regenerate XML

**Comment by foo4thought** [comment]
XML is regenerated from today's AAPB data for selected GUIDs.
[oclc_aapb20241205.xml.gz](https://github.com/user-attachments/files/18029217/oclc_aapb20241205.xml.gz)

**Comment by foo4thought** [comment]
[inventory_oclc20241204.xlsx](https://github.com/user-attachments/files/18029268/inventory_oclc20241204.xlsx)
use & extend this spreadsheet for this kind of selection process in the future
