### ISSUE TITLE
Create GUID records in the AMS2ool

### ISSUE THREAD

**Issue by ekemeyer** [WGBH-MLA/mla-tickets#13]
# Details 
Create GUID records in the AMS2ool

Submitted by: Miranda Villesvik
Priority: High (within the week)
URL: 
Slack message thread: https://wgbh.slack.com/archives/DLXCH9CH0/p1714480475377529

**Comment by foo4thought** [comment]
![image](https://github.com/WGBH-MLA/mla-tickets/assets/516505/06b1fa2f-8408-4487-98ec-5d77021fc6bc)
