### ISSUE TITLE
Display slate and link to visual aid in ams2ool

### ISSUE THREAD

**Issue by ekemeyer** [WGBH-MLA/mla-tickets#17]
# Details 
This is a follow up to a meeting with Kevin and the cataloging team on May 1.  

Context:  We are trying integrate CLAMS output into the cataloging workflow.  The idea is to make CLAMS output available to catalogers through the FileMaker application called "ams2ool" created by Kevin.

There are two parts to the request:

(1) Display the slate (JPG image) from the asset on the main screen for that asset in ams2ool.
(2) Create a link/button that (somehow) displays the visual aid (single HTML file) for the asset in ams2ool.

We are aiming to discuss these changes in the cataloging team meeting on May 29.

For purposes of development and testing, I created slates and visual aids for a few assets from one of the most recent collections delivered by GB.  

These three guids:
cpb-aacip-0b0c3512fff
cpb-aacip-2be1d0f5cec
cpb-aacip-3a3e3b4fea4

Slates:
s3://aapb-aux/slates/cpb-aacip-0b0c3512fff_slate.jpg
s3://aapb-aux/slates/cpb-aacip-3a3e3b4fea4_slate.jpg
s3://aapb-aux/slates/cpb-aacip-2be1d0f5cec_slate.jpg

Visual aids:
s3://aapb-aux/visaids/cpb-aacip-0b0c3512fff_visaid.html
s3://aapb-aux/visaids/cpb-aacip-3a3e3b4fea4_visaid.html
s3://aapb-aux/visaids/cpb-aacip-2be1d0f5cec_visaid.html

Submitted by: Kevin
CC in communications: rebecca_fraimow@wgbh.org/nPriority: Medium (within this month)
URL: 
Slack message thread:

**Comment by foo4thought** [comment]
I created a method to display these resources in FMP; it can easily accommodate others.  Stakeholders have been informed and I'm waiting for more feedback.

**Comment by foo4thought** [comment]
Refinement is done:  companion (resource) window will open only for records that have that resource available; records that lack a particular resource (type) will not open that window. 

Furthermore, the layout (view) used to display a given resource (e.g., slate.jpg) no longer displays http errors but instead displays _"{{LayoutName}} not available"_ at the top of the window, with the GUID
