### ISSUE TITLE
adding GUIDs to the AMS2ool database

### ISSUE THREAD

**Issue by ekemeyer** [WGBH-MLA/mla-tickets#30]
# Details 
use file GUIDstoaddtoAMS2ool_May20-2024.txt

Submitted by: Miranda Villesvik
CC in communications: miranda_villesvik@wgbh.org
Priority: Medium (within this month)
URL: 
Slack message thread: https://wgbh.slack.com/archives/DLXCH9CH0/p1716210350561709

**Comment by foo4thought** [comment]
1,032 records inserted (3 entries from input were rejected because not unique ), then updated all lookup fields
