### ISSUE TITLE
Adding more WIPR assets for ASR processing

### ISSUE THREAD

**Issue by ekemeyer** [WGBH-MLA/mla-tickets#33]
# Details 
Here are 1097 more that can be run with the exact same settings

Submitted by: Owen King
CC in communications: 
Priority: Urgent (within the next 1-2 days)
URL: 
Slack message thread: https://wgbh.slack.com/archives/D057NBHG32S/p1716327233537549

**Comment by foo4thought** [comment]
1. download media from Sony Ci to local file
2. upload media file(s) to s3://asr-media/
3. create zero-byte sized objects with matching keys at s3://asr-listing/
4. insert records to table "aapb_data" of database AAPB_Enhancements
5. update records of table "aapb_data" of database AAPB_Enhancements
6. insert records to table "assignments" of database AAPB_Enhancements to log initial S3 objects
