### ISSUE TITLE
NEH metadata rodeo:  insert new, update old, report each

### ISSUE THREAD

**Issue by ekemeyer** [WGBH-MLA/mla-tickets#39]
# Details 
Insert new data, update/overwrite existing data in the digitized_items table; however, to be safe, we should ensure that we know which records are being overwritten so we can restore them if there’s an error.

Submitted by: Rebecca Fraimow
CC in communications: rebecca_fraimow@wgbh.org
Priority: Medium (within this month)
URL: 
Slack message thread:

**Comment by foo4thought** [comment]
for each of 8 spreadsheet files, I completed these steps:

1. switch layout view to "DIGITIZED_ITEMS", then import the file to add records to this table and performing all auto-enter options; the result is a found set of records in the window
2. process the records with post-import script "newWindowPRODUCTION_related2DIGITIZED_ITEMS" to create a new view (window) & populate field "HIGH_RES_LOCATION" to be leveraged as a primary key (i.e., normally unenforced by the database).  NOTE:  cancel the first dialog, then provide requested metadata for the file name, size, etc.
3. return to layout "DIGITIZED_ITEMS" & perform find - with constricting - for duplicates on that field "HIGH_RES_LOCATION" to reduce the current found set
4. if found set size is zero records, then return to step 1 to process the next file - OR - process these records to be used to ultimately update existing records matching  "HIGH_RES_LOCATION"
5. export relevant fields* to a .MER format text file; this large file will be used again later for the update operation (import to update with-matching on field HIGH_RES_LOCATION)
6. export again to file TMP.MER only the fields HIGH_RES_LOCATION and FILE_NAME; this file will be used only to create the found set of records to be updated with the full set of data created in step #5.
7. change the found set of the original window to "Show Omitted Only"; return to the working window created by step #2 above
8. in the working window created by step #2 above, delete this found set of (duplicate) records, then perform menu option "Show All Records" under the FileMaker menu "Records"
9. import the file created in step #6 to update records without adding; align fields using widget "Matching Names" to engage update of all fields; modify assignment of "HIGH_RES_LOCATION" to "Matching"; turn off all options to perform auto-enter operations; the result is a new found set in the window
10. to create a "safe" copy of this original data, export to a .MER file:  all fields of table "DIGITIZED_ITEMS"
11. import the file created in step #5 to update this set of records; align fields using widget "Matching Names" to engage update of all fields; modify assignment of "HIGH_RES_LOCATION" to "Matching"; turn off all options to perform auto-enter operations
12. close the window created by step #2 and return to the original window

 * fields expressed in the imported spreadsheet file, i.e., not FMP fields like "PrimaryKey" nor "CreatedBy" etc.
