### ISSUE TITLE
GUIDs to add to AMS2ool

### ISSUE THREAD

**Issue by ekemeyer** [WGBH-MLA/mla-tickets#41]
# Details 
Whenever possible, can these be added to AMS2ool: 
cpb-aacip-04a3c93e10b
cpb-aacip-04d25eebbed
cpb-aacip-0582d523812
cpb-aacip-0bcd1268b46
cpb-aacip-0c4cc1e8e32
cpb-aacip-0c4ef45a953
cpb-aacip-0c912867fdf
cpb-aacip-0cdad422a91
cpb-aacip-0ded2c9e4d0
cpb-aacip-0ea55ef734b
cpb-aacip-0f648682c98
cpb-aacip-11dfdbd98a7
cpb-aacip-13d649643d4
cpb-aacip-170ec456a3f
cpb-aacip-171ff24419f
cpb-aacip-172471b433c
cpb-aacip-17ac0d21f3e
cpb-aacip-18c0baaed53
cpb-aacip-19d92f9d91e
cpb-aacip-1a9692044f1
cpb-aacip-1b1d1dd1691
cpb-aacip-1b71d480ce9
cpb-aacip-1ba3d85577c
cpb-aacip-1c056136d5b
cpb-aacip-1d9c2b10f48
cpb-aacip-1dc46622358
cpb-aacip-1e3eaad5f75
cpb-aacip-1e46f909733
cpb-aacip-2478cff5674
cpb-aacip-27f6fe6485d
cpb-aacip-2a11e320cb9
cpb-aacip-2a9429ccb44
cpb-aacip-2ba5f10329c
cpb-aacip-2ce469e05b2
cpb-aacip-2f61f266e5a
cpb-aacip-3056d3bb262
cpb-aacip-31aa0acfead
cpb-aacip-322bde477b0
cpb-aacip-3302254b176
cpb-aacip-337031c7b3b
cpb-aacip-33a84993d7e
cpb-aacip-358a95b9beb
cpb-aacip-37d8654cdb6
cpb-aacip-3869a530a59
cpb-aacip-3c5ca66f0ba
cpb-aacip-4028e0f91e3
cpb-aacip-42f98fbdbb3
cpb-aacip-4385310065c
cpb-aacip-447ed2345b2
cpb-aacip-46335512cc2
cpb-aacip-47523142b46
cpb-aacip-4aea74e9ed1
cpb-aacip-4b311af962c
cpb-aacip-4cadc20742c
cpb-aacip-4d569694a5f
cpb-aacip-509ef77618b
cpb-aacip-5382e947e1d
cpb-aacip-5405fd64cab
cpb-aacip-540f0d6c7bf
cpb-aacip-5608f71565b
cpb-aacip-57081dc9bc1
cpb-aacip-57f189b497b
cpb-aacip-58690a85651
cpb-aacip-5a4eb978a33
cpb-aacip-5d8a4557b4f
cpb-aacip-5e3c04e24f0
cpb-aacip-5f4d8b00b8f
cpb-aacip-5ff86186048
cpb-aacip-61d419f2f74
cpb-aacip-620f6c36975
cpb-aacip-62f2814081d
cpb-aacip-63ace8011e0
cpb-aacip-651398542c8
cpb-aacip-6835cac5ff1
cpb-aacip-684f18ed3fe
cpb-aacip-68d1f3cd142
cpb-aacip-692530bfc9d
cpb-aacip-6b00f6131d2
cpb-aacip-6c1ff6c60ba
cpb-aacip-6f1b8662684
cpb-aacip-6f8650a28ab
cpb-aacip-7043972c28d
cpb-aacip-743585707da
cpb-aacip-74911376dc5
cpb-aacip-749ae227d54
cpb-aacip-76ba95b6a55
cpb-aacip-76c271444a6
cpb-aacip-7822e434345
cpb-aacip-79444948e4c
cpb-aacip-7c4a3a56efd
cpb-aacip-80319a15c27
cpb-aacip-809a2320cd6
cpb-aacip-814185075a5
cpb-aacip-8166905c3d6
cpb-aacip-850368398db
cpb-aacip-85f93d8e91e
cpb-aacip-87f6f6539f1
cpb-aacip-880710bf9c2
cpb-aacip-89456dac683
cpb-aacip-8952513e6b1
cpb-aacip-8b0361bb1a9
cpb-aacip-8b5fcd98e78
cpb-aacip-91a2b289ca5
cpb-aacip-91bc4840dc6
cpb-aacip-94ed31c8366
cpb-aacip-95ffcc39073
cpb-aacip-9855ac605cf
cpb-aacip-985f0b2b705
cpb-aacip-9a2fceff725
cpb-aacip-9a48c790763
cpb-aacip-9b00f028772
cpb-aacip-9c8ff56453f
cpb-aacip-9dcc50dc2a6
cpb-aacip-9e0450ed3f1
cpb-aacip-a1de65249e5
cpb-aacip-a2625034b57
cpb-aacip-a4831816fff
cpb-aacip-a4fdf695508
cpb-aacip-a6f82832fe6
cpb-aacip-a7f12cb6378
cpb-aacip-a827354e913
cpb-aacip-a86fdf7b9d9
cpb-aacip-a8a288a186b
cpb-aacip-a8b186fa8fa
cpb-aacip-aca3489e351
cpb-aacip-acd242d82aa
cpb-aacip-ae11e0ac731
cpb-aacip-afc227b1fbe
cpb-aacip-b0608d240f7
cpb-aacip-b61eb25e210
cpb-aacip-b6521e7205b
cpb-aacip-b97d4fb9322
cpb-aacip-bd71f172c1f
cpb-aacip-bddb0b98f9f
cpb-aacip-be87a3f8362
cpb-aacip-beabd0ebcf9
cpb-aacip-bf92c926cd7
cpb-aacip-c4191c7e417
cpb-aacip-c474e8d8f53
cpb-aacip-c6f5f1c3822
cpb-aacip-c74f3e239fe
cpb-aacip-c852e8d6f94
cpb-aacip-c9c848d7ee5
cpb-aacip-c9fd46ade74
cpb-aacip-ca6b1dcb58d
cpb-aacip-cd4d3c60845
cpb-aacip-cda40a25f5e
cpb-aacip-cdab973e706
cpb-aacip-d1378ea2265
cpb-aacip-d2f96bc26bf
cpb-aacip-d4992db83d1
cpb-aacip-d621cc0d0a6
cpb-aacip-d6e8b0edbb1
cpb-aacip-d7169542c4e
cpb-aacip-d7633584f07
cpb-aacip-d9ccf56b397
cpb-aacip-dc6a7efa59d
cpb-aacip-deeb6fe05be
cpb-aacip-df05653172d
cpb-aacip-e12ba190c2e
cpb-aacip-e1456b420be
cpb-aacip-e16bdcc5417
cpb-aacip-e4931cb9f14
cpb-aacip-e4f6c303d37
cpb-aacip-eb018ac8bcb
cpb-aacip-ede77d10497
cpb-aacip-ee94b19e836
cpb-aacip-f080a84cdc8
cpb-aacip-f2b319e85b4
cpb-aacip-f3a04a63488
cpb-aacip-f3ba54463ab
cpb-aacip-f55bc027a43
cpb-aacip-f909df3f77d
cpb-aacip-fc663883e3b
cpb-aacip-fe980ffcef2
cpb-aacip-fee9baf4555
cpb-aacip-ff570f7dc83

Submitted by: Caroline
CC in communications: 
Priority: High (within the week)
URL: 
Slack message thread:

**Comment by foo4thought** [comment]
Done
