### ISSUE TITLE
Remove 'Option to Identify Deprecated Catalog Records' window from default import process and make this instead a separate operation

### ISSUE THREAD

**Issue by ekemeyer** [WGBH-MLA/mla-tickets#49]
# Details 
When importing data from S3 buckets in BucketBowser, the import process includes a pop-up window that offers the option to identify items in the bucket that are no longer valid. Although a good idea in theory, in practice this makes it very easy to accidentally click 'OK' on this option and trigger a very long data assess/compare operation that occupies Filemaker and puts other work to a halt. This process should be moved out of the default data import workflow and should instead be a separate button or script that the user can trigger to run at times when Filemaker is not otherwise in use. 

Submitted by: Kevin
CC in communications: 
Priority: Medium (within this month)
URL: 
Slack message thread:

**Comment by foo4thought** [comment]
1. Discussed with Rebecca
2. Explored option to run script apart from where it's currently offered, but it's unsuitable as a standalone operation.
3. Disabled dialog for common users; it is displayed only to the db admin.
