### ISSUE TITLE
allowing for file name/path edits in NEH Workflow Tracking Database

### ISSUE THREAD

**Issue by ekemeyer** [WGBH-MLA/mla-tickets#61]
# Details 
We need a way to update file names and paths in the NEH Workflow Tracking Database to account for errors in the metadata provided by George Blood without re-ingesting the entire metadata sheet. Currently, fields in the Digitized_Items layout are not modifiable without a data ingest. Kevin proposes making the 'DIGITIZED_ITEMS::File Name' field independently modifiable and using that to update all related technical information. 

Submitted by: Rebecca Fraimow
CC in communications: kevin_carter@wgbh.org
Priority: Medium (within this month)
URL: 
Slack message thread:

**Comment by foo4thought** [comment]
discussed with Rebecca via slack; proposed solution, implemented and tested.

1. created application-level list of authorized editors of target field 
2. modified field-level access to fields within security profile used by MLA staff
3. modified table-level access to target field within security profile used by MLA staff
4. imposed schema-level validation for target field
5. created script to be run by GUI-level event assigned to target field
6. assigned script to instance of target field on user-facing GUI
7. tested operation using security profile used by MLA staff
8. communicated outcomes and outlooks with Rebecca for its use
