### ISSUE TITLE
BirdNote Transcripts 2023

### ISSUE THREAD

**Issue by ekemeyer** [WGBH-MLA/mla-tickets#63]
### Because

BirdNote episodes from 2023 need transcripts attached so they appear on AAPB
[BirdNote_2023_transcripts.zip](https://github.com/user-attachments/files/16442111/BirdNote_2023_transcripts.zip)

### Done when

Transcripts are on AAPB

### Additional context

From Miranda email 7/31/24

**Comment by foo4thought** [comment]
1. uncompress ZIP archive
2. inspect files
3. rename files for upload using AAPB convention
4. list GUIDs
5. test S3 for existing
6. upload files to S3 for transcripts/GUID/ and to S3 for backup/transcripts/GUID/
7. create spreadsheet for updating asset metadata on ams2
8. upload spreadsheet as "batch" on ams2
9. "push" GUIDs from ams2 to AAPB
10. import GUIDs to AAPB_Enhancements database
11. inspect records in database for QA
12. report outcomes
