### ISSUE TITLE
Adding OPB to the AMS2ool

### ISSUE THREAD

**Issue by ekemeyer** [WGBH-MLA/mla-tickets#66]
# Details 
We've got some new Mellon GUIDs that are ready to be added to the AMS2ool database!
(see email dated 8/9/2024) If someone (Kevin?) can add them there, that would be much appreciated,
Thanks!

Submitted by: Miranda!
CC in communications: 
Priority: Medium (within this month)
URL: 
Slack message thread:

**Comment by foo4thought** [comment]
All but two were added and updated with metadata from ams2

Already recorded in the system and not further processed:

cpb-aacip-63a04ec25b6
cpb-aacip-9d14e9ffc15
