### ISSUE TITLE
Updating 'bucketbowser2lto.sh' script for use with MLA production files

### ISSUE THREAD

**Issue by ekemeyer** [WGBH-MLA/mla-tickets#7]
# Details 
We need an update to the existing Kevin-built bucketbowser2lto.sh script (originally intended to pull George Blood-digitized master files from Object Store to LTO) that will allow us to write GBH production files stored in S3 to LTO on a Windows machine without assuming George Blood's file delivery structure or the existence of pre-generated metadata. This is something I expect will take a certain amount of back-and-forth and direct testing with Kevin. 

Submitted by: Rebecca
Priority: Medium (within this month)
URL: 
Slack message thread:

**Comment by foo4thought** [comment]
I spoke with Rebecca and what she wants is an earlier version of script.  I slacked it to her
