### ISSUE TITLE
NewsHour PBCore XML records

### ISSUE THREAD

**Issue by ekemeyer** [WGBH-MLA/mla-tickets#70]
# Details 
Our partners at NewsHour have asked for a copy of all of their PBCore XML as it exists on the AAPB

Submitted by: Rebecca Fraimow
CC in communications: 
Priority: High (within the week)
URL: 
Slack message thread:

**Comment by foo4thought** [comment]
`mylocal:newshour_xml_aapb_20240830 kevin_carter$ rows=100;start=0;while [ "$(curl -sS 'https://americanarchive.org/api.json?fl=id,xml&rows='"$rows"'&q=%28contributing_organizations:%22NewsHour+Productions+%28DC%29%22%20AND%20access_types:all%29&start='"$start" | tee >(jq -r '.response.docs[].id' >> ids.txt) $start.json | jq -r '.response.numFound')" -gt $start ];do start=$[$start+$rows];done`

**Comment by foo4thought** [comment]
`mylocal:newshour_xml_aapb_20240830 kevin_carter$ for jfile in $(ls -1 *.json);do for docnum in $(seq 0 $[$(jq -r '.response.docs|length' "$jfile")-1] );do guid=$(jq -r --arg docnum "$docnum" '.response.docs[($docnum|tonumber)].id' "$jfile" | tr '/_' '-');jq -r --arg docnum "$docnum" '.response.docs[($docnum|tonumber)].xml' "$jfile" > $guid.xml;done;zip -m newshour_aapb_pbcore_xml.zip *.xml ;done`

**Comment by foo4thought** [comment]
[newshour_aapb_pbcore_xml.zip](https://github.com/user-attachments/files/16820049/newshour_aapb_pbcore_xml.zip)



[ids.txt](https://github.com/user-attachments/files/16820058/ids.txt)
