### ISSUE TITLE
Nebraska Public Media transcripts reported wacky

### ISSUE THREAD

**Issue by ekemeyer** [WGBH-MLA/mla-tickets#75]
# Details 
nonexistent phrase repeating a bunch of times at the beginning of the transcript

Submitted by: Miranda Villesvik
CC in communications: 
Priority: Urgent (within the next 1-2 days)
URL: https://americanarchive.org/catalog/cpb-aacip-4c3fbb2aaf7 and many more
Slack message thread:

**Comment by foo4thought** [comment]
1. retrieved Sony ID from each GUID
2. performed download from Sony Ci and upload to AWS bucket asr-media
3. performed upload of media tickets to special prefix location in AWS bucket asr-listing
4. modified my local file s3keyprefix.txt to use the prefix location 
5. monitored progress
6. reported initial progress (no improvement) and final result (no improvement) to Miranda V + contact at Nebraska Public Media
7. provided JSON transcript files to NPM with instructions for editing

**Comment by foo4thought** [comment]
- deleted from AWS s3 all objects related to this project
- restored my local file s3keyprefix to the default value of cpb-aacip
