### ISSUE TITLE
WETA inventory 

### ISSUE THREAD

**Issue by ekemeyer** [WGBH-MLA/mla-tickets#79]
# Details 
Is it possible to get the AAPB search results linked below in an excel spreadsheet? Basically it's WETA-TV as producing org, in all its iterations (it's listed in, I think, 3 different ways under producing orgs.; hopefully I selected them all. I don't need the WETA radio stuff). I need to compare the results with a new inventory we got from WETA. I used to know how to do this but can't remember! I mainly need GUIDs, titles, dates, and descriptions if they're there. Let me know if I can clarify anything. Thanks! 

Submitted by: Michelle
CC in communications: 
Priority: High (within the week)
URL: https://americanarchive.org/catalog?f%5Baccess_types%5D%5B%5D=digitized&f%5Bproducing_organizations%5D%5B%5D=WETA+OR+WETA-TV+OR+WETA-TV+%28Television+station+%3A+Washington%2C+D.C.%29
Slack message thread:

**Comment by foo4thought** [comment]
`mylocal:report_weta_aapb20240917 kevin_carter$ rows=100;start=0;while [ "$start" -lt "$(curl -sS 'https://americanarchive.org/api.json?fl=id,xml&rows='$rows'&q=%28access_types:digitized%20AND%20producing_organizations:WETA%29%20OR%20%28access_types:digitized%20AND%20producing_organizations:WETA-TV%29%20OR%20%28access_types:digitized%20AND%20producing_organizations:%22WETA-TV%20%28Television%20station%20%3A%20Washington%2C%20D.C.%29%22%29&start='$start | tee $start.json >(jq -r --arg start "$start.json" '[$start,(.response.docs|length)]|@tsv' >> docs_counts.txt ) | jq -r '.response.numFound')" ];do sleep 1;start=$[$start+$rows];done 
mylocal:report_weta_aapb20240917 kevin_carter$ for f in $(ls -1 *.json);do json=$(cat $f);dt=$(echo "$json" | jq -r '.response.docs|length');for dn in $(seq 0 "$dt");do guid=$(echo "$json" | jq -r --arg dn $dn '.response.docs[($dn|tonumber)].id');echo "$json" | jq -r --arg dn $dn '.response.docs[($dn|tonumber)].xml' > xml/$(echo $guid | tr '_' '-').xml;done;done
mylocal:report_weta_aapb20240917 kevin_carter$ ./report.sh 
mylocal:report_weta_aapb20240917 kevin_carter$ gzip report.txt`

[report.txt.gz](https://github.com/user-attachments/files/17032794/report.txt.gz)
