### ISSUE TITLE
Add the following GUIDs to AMSool :)

### ISSUE THREAD

**Issue by ekemeyer** [WGBH-MLA/mla-tickets#81]
# Details 
Hellooooo! Is it possible to add the following to AMS2ool please? 
I'm leaving for Brazil on Oct. 7th so even though these don't have to be added to the database this week, I do have to finish reviewing them before I leave to meet George Blood's deadline. Thank you :D
cpb-aacip-01441f7d0cf.mp3
cpb-aacip-02e0b39f7dc.mp3
cpb-aacip-033b901eaae.mp3
cpb-aacip-03b71de652f.mp3
cpb-aacip-04476934f6e.mp3
cpb-aacip-04b09dbc4f1.mp3
cpb-aacip-04d0f21645c.mp3
cpb-aacip-04f96365cc7.mp3
cpb-aacip-07242482e2d.mp3
cpb-aacip-09f301d042f.mp3
cpb-aacip-0aabf90c361.mp3
cpb-aacip-0c8a67d73fa.mp3
cpb-aacip-0dd15b2fe88.mp3
cpb-aacip-0eee2159825.mp3
cpb-aacip-0f69aca88cb.mp3
cpb-aacip-108432d57f2.mp3
cpb-aacip-10fcd53ac0f.mp3
cpb-aacip-139790aeeef.mp3
cpb-aacip-13f9006a22c.mp3
cpb-aacip-146e0d73836.mp3
cpb-aacip-14aad48f097.mp3
cpb-aacip-161c3d9b943.mp3
cpb-aacip-177513c3390.mp3
cpb-aacip-185ee37bab8.mp3
cpb-aacip-1891be46a21.mp3
cpb-aacip-198b7d30b98.mp3
cpb-aacip-19ab31b5fc4.mp3
cpb-aacip-1a170020968.mp3
cpb-aacip-1a1e10710d1.mp3
cpb-aacip-1ac3884676b.mp3
cpb-aacip-1b11e4a201c.mp3
cpb-aacip-1c5fcfb6d2e.mp3
cpb-aacip-1db5e4aea01.mp3
cpb-aacip-1eb18a9ebce.mp3
cpb-aacip-1f4227455f7.mp3
cpb-aacip-20b0126dde4.mp3
cpb-aacip-21230f57f58.mp3
cpb-aacip-21759bb23d2.mp3
cpb-aacip-23b4e99799e.mp3
cpb-aacip-242155f340a.mp3
cpb-aacip-24de3318a90.mp3
cpb-aacip-25ceaa5ef07.mp3
cpb-aacip-2603d72153f.mp3
cpb-aacip-272dbc700e9.mp3
cpb-aacip-27357616b08.mp3
cpb-aacip-278d068ca46.mp3
cpb-aacip-28a5c8f6205.mp3
cpb-aacip-2907819761d.mp3
cpb-aacip-291fd8072fd.mp3
cpb-aacip-29a64540350.mp3
cpb-aacip-2b6173751b6.mp3
cpb-aacip-2b8945cf4a3.mp3
cpb-aacip-2bddd0d8096.mp3
cpb-aacip-2dcc8d78d7a.mp3
cpb-aacip-2e05f6a9116.mp3
cpb-aacip-2e6c1cf5922.mp3
cpb-aacip-2f49ad74608.mp3
cpb-aacip-302a7afa455.mp3
cpb-aacip-30be15e1af1.mp3
cpb-aacip-322dc2cd659.mp3
cpb-aacip-334aeb225f0.mp3
cpb-aacip-339050d2e9a.mp3
cpb-aacip-33b9af8375d.mp3
cpb-aacip-35b96f7ee0c.mp3
cpb-aacip-360bf0ebc8c.mp3
cpb-aacip-3613c40d3d2.mp3
cpb-aacip-364ac4e4356.mp3
cpb-aacip-367d75ca061.mp3
cpb-aacip-376aa9849bd.mp3
cpb-aacip-37fab5a783d.mp3
cpb-aacip-393b5a24f36.mp3
cpb-aacip-3accffa3030.mp3
cpb-aacip-3b1fe9db887.mp3
cpb-aacip-3b267221bb5.mp3
cpb-aacip-3b5cba1186b.mp3
cpb-aacip-3c42af94512.mp3
cpb-aacip-3cc381faa7a.mp3
cpb-aacip-3d99a613657.mp3
cpb-aacip-3ded70eca18.mp3
cpb-aacip-3f628acf1ad.mp3
cpb-aacip-4219591034d.mp3
cpb-aacip-4306e7145d4.mp3
cpb-aacip-4639c784493.mp3
cpb-aacip-4701787b4f5.mp3
cpb-aacip-491ec3b7e2f.mp3
cpb-aacip-4925caaf4df.mp3
cpb-aacip-49ab2330d60.mp3
cpb-aacip-4a0674e232c.mp3
cpb-aacip-4b485019a8b.mp3
cpb-aacip-4c496c8c7b0.mp3
cpb-aacip-4dc973b505a.mp3
cpb-aacip-4eb2a9d8da2.mp3
cpb-aacip-5202ee80575.mp3
cpb-aacip-53f49ad69db.mp3
cpb-aacip-53fcd6aa0d8.mp3
cpb-aacip-5435d9126e2.mp3
cpb-aacip-54a027b337a.mp3
cpb-aacip-55e453a2745.mp3
cpb-aacip-57876aabfc9.mp3
cpb-aacip-5802ed28bf9.mp3
cpb-aacip-588fb2030a2.mp3
cpb-aacip-5991489861d.mp3
cpb-aacip-59bea9f06d5.mp3
cpb-aacip-5bfab0b9a1f.mp3
cpb-aacip-5edc0ffa6f5.mp3
cpb-aacip-5fb49955fcd.mp3
cpb-aacip-5fe9b52e2e6.mp3
cpb-aacip-5ff2e06937f.mp3
cpb-aacip-613197cd261.mp3
cpb-aacip-615e542b74f.mp3
cpb-aacip-61c1e38cff5.mp3
cpb-aacip-628669b39ba.mp3
cpb-aacip-62e2bcebf2f.mp3
cpb-aacip-6311576ad3e.mp3
cpb-aacip-6399104bb55.mp3
cpb-aacip-653c807c0c1.mp3
cpb-aacip-66df99d454f.mp3
cpb-aacip-6775d2d562a.mp3
cpb-aacip-685dcbd16c6.mp3
cpb-aacip-68e5a6656c6.mp3
cpb-aacip-6939641d4a3.mp3
cpb-aacip-6c492ce5031.mp3
cpb-aacip-6cb2b669b43.mp3
cpb-aacip-6d3e19fe5d2.mp3
cpb-aacip-6e7977bf8ef.mp3
cpb-aacip-6e92b8735d7.mp3
cpb-aacip-6f8f4b30981.mp3
cpb-aacip-6fc4655e8ad.mp3
cpb-aacip-705fc1e929a.mp3
cpb-aacip-70dd4492404.mp3
cpb-aacip-72412522521.mp3
cpb-aacip-016b47a789c.mp3
cpb-aacip-02c20b34a6c.mp3
cpb-aacip-0937c186f67.mp3
cpb-aacip-132b8c6405a.mp3
cpb-aacip-146d8c64cab.mp3
cpb-aacip-1f1377e6100.mp3
cpb-aacip-1fae0f2b997.mp3
cpb-aacip-2dbada6d483.mp3
cpb-aacip-2dffdae68b3.mp3
cpb-aacip-3e50ec82032.mp3
cpb-aacip-4cda1b3863d.mp3
cpb-aacip-5ba1f27303b.mp3
cpb-aacip-5eeef593319.mp3
cpb-aacip-61318a40872.mp3
cpb-aacip-638923e1460.mp3
cpb-aacip-6d9234a4c88.mp3
cpb-aacip-700308d9842.mp3
cpb-aacip-051c0115692.mp4
cpb-aacip-069132ccae9.mp4
cpb-aacip-077c28ed4e4.mp4
cpb-aacip-08defe4c601.mp4
cpb-aacip-098b3d99f9a.mp4
cpb-aacip-0b5f3d0dd61.mp4
cpb-aacip-110354e6d8a.mp4
cpb-aacip-15fda8fbbf4.mp4
cpb-aacip-170812bd13f.mp4
cpb-aacip-1c0e004e20a.mp4
cpb-aacip-226856eeac5.mp4
cpb-aacip-290e59ef445.mp4
cpb-aacip-30d278a13b1.mp4
cpb-aacip-39288de2aba.mp4
cpb-aacip-3df48de458c.mp4
cpb-aacip-4c0d4ce1bfb.mp4
cpb-aacip-502ae5ea416.mp4
cpb-aacip-51f466599ca.mp4
cpb-aacip-5722a48b98d.mp4
cpb-aacip-5743b0bd2f0.mp4
cpb-aacip-5ab8808575b.mp4
cpb-aacip-5b74b57892e.mp4
cpb-aacip-5da71e13221.mp4
cpb-aacip-5e5bbbe6fd2.mp4
cpb-aacip-67a8478a894.mp4
cpb-aacip-6ce08b58778.mp4
cpb-aacip-71e348386e0.mp4
cpb-aacip-7a1120f04e8.mp4
cpb-aacip-7f72dbcd151.mp4
cpb-aacip-80413daf4a3.mp4
cpb-aacip-5d96686051a.mp4
cpb-aacip-72fc075f9ba.mp3
cpb-aacip-72ffdecd75f.mp3
cpb-aacip-73c4a4db880.mp3
cpb-aacip-751102dca95.mp3
cpb-aacip-75823116b89.mp3
cpb-aacip-76dc7ac8df4.mp3
cpb-aacip-7728a7dcd07.mp3
cpb-aacip-780adaafb23.mp3
cpb-aacip-784b88a7ac0.mp3
cpb-aacip-794ffce6ba3.mp3
cpb-aacip-796ab776b4e.mp3
cpb-aacip-798335de364.mp3
cpb-aacip-7aa7f771c03.mp3
cpb-aacip-7b1c2203d16.mp3
cpb-aacip-7d29b1a3ece.mp3
cpb-aacip-7e0649c4a9b.mp3
cpb-aacip-7e8a314c063.mp3
cpb-aacip-7ed968af986.mp3
cpb-aacip-824403667f1.mp3
cpb-aacip-82c19e84ccd.mp3
cpb-aacip-82ccb4824b9.mp3
cpb-aacip-84fa79321de.mp3
cpb-aacip-85fe0998ab0.mp3
cpb-aacip-884488141d5.mp3
cpb-aacip-88a14199f1e.mp3
cpb-aacip-8a549c4e03b.mp3
cpb-aacip-8ac18b86a3d.mp3
cpb-aacip-8d0004ef2d2.mp3
cpb-aacip-9011127f2ca.mp3
cpb-aacip-9016c6a6921.mp3
cpb-aacip-9205b44b71f.mp3
cpb-aacip-92831296a33.mp3
cpb-aacip-930e97ea2e7.mp3
cpb-aacip-93c53fbf4c8.mp3
cpb-aacip-941bf1a3d59.mp3
cpb-aacip-94e4c0c6b8b.mp3
cpb-aacip-95b90cb486e.mp3
cpb-aacip-95e8d09ffef.mp3
cpb-aacip-97e649e23a0.mp3
cpb-aacip-997aace6957.mp3
cpb-aacip-99dbb17d2e9.mp3
cpb-aacip-9ed55ecd16d.mp3
cpb-aacip-9f1ab3e1cdd.mp3
cpb-aacip-9fc4b83101b.mp3
cpb-aacip-a00daec1932.mp3
cpb-aacip-a38c74bffab.mp3
cpb-aacip-a4eae6f3fae.mp3
cpb-aacip-a53ce4bf8d5.mp3
cpb-aacip-a5583aef397.mp3
cpb-aacip-a7fbbce8c2c.mp3
cpb-aacip-a898ce06ac8.mp3
cpb-aacip-a976cf54b1b.mp3
cpb-aacip-aa2cc11a317.mp3
cpb-aacip-aa3e3aaa728.mp3
cpb-aacip-aae30f6d1f0.mp3
cpb-aacip-abb7673a48c.mp3
cpb-aacip-ad108cf64ff.mp3
cpb-aacip-ade24e24dfc.mp3
cpb-aacip-adfed61d125.mp3
cpb-aacip-af101803574.mp3
cpb-aacip-af24b80ce26.mp3
cpb-aacip-b003fcf770f.mp3
cpb-aacip-b0112620314.mp3
cpb-aacip-b4b1fce6a59.mp3
cpb-aacip-b4b9d3ecfb9.mp3
cpb-aacip-b59853de9de.mp3
cpb-aacip-b59ab07d897.mp3
cpb-aacip-b5d0b5a299e.mp3
cpb-aacip-b5f25bc52ba.mp3
cpb-aacip-b6fbe916d57.mp3
cpb-aacip-b90216b0a57.mp3
cpb-aacip-b9c9ddf983d.mp3
cpb-aacip-ba755379b96.mp3
cpb-aacip-baf23a214b3.mp3
cpb-aacip-bb36083729f.mp3
cpb-aacip-bb4bbcfce9e.mp3
cpb-aacip-bbd264cbea2.mp3
cpb-aacip-bc43bc3e53a.mp3
cpb-aacip-bf8bfeb4e58.mp3
cpb-aacip-bf94c0a92de.mp3
cpb-aacip-c1da855c081.mp3
cpb-aacip-c2b9d262278.mp3
cpb-aacip-c2e60adab62.mp3
cpb-aacip-c42df9fc0e2.mp3
cpb-aacip-c59b9cc2ce3.mp3
cpb-aacip-c641b5b98c8.mp3
cpb-aacip-cbb1b26289e.mp3
cpb-aacip-cc1aca61dbf.mp3
cpb-aacip-cd69579c32e.mp3
cpb-aacip-ce07a20c774.mp3
cpb-aacip-ce8d9daf7bf.mp3
cpb-aacip-d10faf73c10.mp3
cpb-aacip-d1748781720.mp3
cpb-aacip-d1e41193760.mp3
cpb-aacip-d2fb5590743.mp3
cpb-aacip-d39b1b7eb37.mp3
cpb-aacip-dadf84c1737.mp3
cpb-aacip-db138c84a79.mp3
cpb-aacip-dcf09492a15.mp3
cpb-aacip-dd6dbb65dbd.mp3
cpb-aacip-df4e8c12f62.mp3
cpb-aacip-dfab93e8aa0.mp3
cpb-aacip-dfd28bf980b.mp3
cpb-aacip-e0b4ada74d2.mp3
cpb-aacip-e214ea1b1d2.mp3
cpb-aacip-e2c6b7084ca.mp3
cpb-aacip-e396213447b.mp3
cpb-aacip-e83bf95e1cd.mp3
cpb-aacip-e854e36ac3b.mp3
cpb-aacip-e967b08bbf6.mp3
cpb-aacip-eb77a04f541.mp3
cpb-aacip-ebb10b3f83f.mp3
cpb-aacip-ed9f69a534f.mp3
cpb-aacip-edb158c6b12.mp3
cpb-aacip-ef086926cff.mp3
cpb-aacip-f0564255ef9.mp3
cpb-aacip-f0f829261f5.mp3
cpb-aacip-f1edba2c8f6.mp3
cpb-aacip-f4c18141ed4.mp3
cpb-aacip-f6e17f83697.mp3
cpb-aacip-f73ae4c10a8.mp3
cpb-aacip-f859dee511d.mp3
cpb-aacip-fbafb2036ae.mp3
cpb-aacip-fbc5f029eae.mp3
cpb-aacip-fc2d37d0221.mp3
cpb-aacip-fc385d1cec1.mp3
cpb-aacip-fca90384bab.mp3
cpb-aacip-fd178af44f6.mp3
cpb-aacip-fd79e52dcdd.mp3
cpb-aacip-ffb6b2bfd37.mp3
cpb-aacip-dea82cde886.mp4
cpb-aacip-75534327003.mp3
cpb-aacip-784d1a9fece.mp3
cpb-aacip-8a7bc7cf491.mp3
cpb-aacip-8b836e05662.mp3
cpb-aacip-8bb0f9ee0e7.mp3
cpb-aacip-914c50dc7ff.mp3
cpb-aacip-925d7f6d7ea.mp3
cpb-aacip-9a51d2d0ce7.mp3
cpb-aacip-9ae867dd2c8.mp3
cpb-aacip-ab92bc3e174.mp3
cpb-aacip-b80e5dbe47e.mp3
cpb-aacip-b86bd921030.mp3
cpb-aacip-beb557e2acc.mp3
cpb-aacip-bed2e943f35.mp3
cpb-aacip-e00354d5a1a.mp3
cpb-aacip-e76ac1c0fb1.mp3
cpb-aacip-ee52f9506b4.mp3
cpb-aacip-824c377bb51.mp4
cpb-aacip-8ad01d9c0ca.mp4
cpb-aacip-8d74962e4f6.mp4
cpb-aacip-8e3a082af22.mp4
cpb-aacip-974dc53c6dd.mp4
cpb-aacip-a112965192f.mp4
cpb-aacip-a5d7c7cd25b.mp4
cpb-aacip-a71e84b26b2.mp4
cpb-aacip-a7e8995cbe5.mp4
cpb-aacip-a972ed87ef9.mp4
cpb-aacip-aa2afda98a1.mp4
cpb-aacip-b2141acb31c.mp4
cpb-aacip-b5844b9416f.mp4
cpb-aacip-b6f374219f8.mp4
cpb-aacip-c1bfd99f227.mp4
cpb-aacip-c2f25d46c70.mp4
cpb-aacip-c5e884de94b.mp4
cpb-aacip-caba8af357f.mp4
cpb-aacip-cc8d092ebc5.mp4
cpb-aacip-cfe62ca6223.mp4
cpb-aacip-d30c6611dfd.mp4
cpb-aacip-d5d9e18db4d.mp4
cpb-aacip-d6a72b8f418.mp4
cpb-aacip-d9cc00ef3b3.mp4
cpb-aacip-e11e43be4ad.mp4
cpb-aacip-e48900be3cf.mp4
cpb-aacip-e665d324412.mp4
cpb-aacip-e8203ab2039.mp4
cpb-aacip-f2440e6a2be.mp4

Submitted by: Caroline
CC in communications: 
Priority: High (within the week)
URL: 
Slack message thread:

**Comment by foo4thought** [comment]
this interface makes it difficult to select so many GUIDs for copy/paste elsewhere.  I figured it out (start selection, scroll to bottom and shift-click the end of the selection)
