### ISSUE TITLE
Add GUIDs to ams2ool database

### ISSUE THREAD

**Issue by ekemeyer** [WGBH-MLA/mla-tickets#85]
# Details 
emailed file "GUIDstoaddtoAMS2ool_Sept2024.txt" 

Submitted by: Miranda Villesvik
CC in communications: 
Priority: Medium (within this month)
URL: 
Slack message thread:

**Comment by foo4thought** [comment]
the file of GUIDs is not in my email

**Comment by foo4thought** [comment]
Miranda will email the GUIDs to me

**Comment by foo4thought** [comment]
256 items added to table "ams2ool" and post-processed to add ams2 metadata
