### ISSUE TITLE
Scripting to assist with Pacifica colletion ingest

### ISSUE THREAD

**Issue by ekemeyer** [WGBH-MLA/mla-tickets#87]
# Details 
Given many thousands of items on drive having related metadata in spreadsheets, process the spreadsheets to generate scripts and CSV to help ingest everything into AAPB

Submitted by: Rebecca Fraimow
CC in communications: rebecca_fraimow@wgbh.org
Priority: Urgent (within the next 1-2 days)
URL: 
Slack message thread:

**Comment by foo4thought** [comment]
1. spreadsheets are enhanced with new column "use_this" :  as requested, its value "1" indicates rows with largest value for a file name value in column B ;
2. the formula for "use_this" was similar to: =IF($G2=MAX(CHOOSECOLS(FILTER($B2:$G4909,$B2=$B2:$B4909),6)),1,0)
3. "use_this" formula values replaced formulas in cell contents for better performance
4. running applescript reads open spreadsheets, engages operator, then creates two files for further use;
5. files created are BASH script (remember to make those executable) and TSV with metadata for header and other rows;
6. each BASH script queries its operator for input/output paths and does simple sanity checks on those;
7. each BASH script does NOT test the target file system before copying files; it will report errors to a file for each line.
8. all products delivered to Rebecca & Raananah Sarid-Segal via slack


https://github.com/user-attachments/assets/ef414426-58b3-4185-bad4-c805b530e3f5
[excel_work_pacifica.applescript.txt](https://github.com/user-attachments/files/17234838/excel_work_pacifica.applescript.txt)
