### ISSUE TITLE
update BucketBowser to allow for searching by folder within file path

### ISSUE THREAD

**Issue by ekemeyer** [WGBH-MLA/mla-tickets#88]
# Details 
BucketBowser currently only has the capacity to search by file name or by full AWS key; it would simplify searches of GBH digital content to be able to search by folder names within the full key. Kevin and I chatted about this briefly and he says it should be pretty low lift to implement

Submitted by: Rebecca Fraimow
CC in communications: 
Priority: Medium (within this month)
URL: 
Slack message thread:

**Comment by foo4thought** [comment]
1. surveyed existing structures & decided to just repurpose an existing, already-indexed field;
2. modified the formula of the trigger that auto-enters the value;
3. now updating existing 11.7M records;
4. data format lists by line the "/" delimited path segments in reverse order - L-R becomes top to bottom
5. UI changes will add the letter "s" to the field label, becoming  **Key Basenames**
`Let ( [ modKeyString = Substitute ( Substitute ( Trim ( Substitute ( Substitute ( objectStore::Key ; " " ; "|" ) ; "/" ; " " ) ) ; " " ; "/" ) ; "|" ; " " )  ] ; 
 
  While ( 
	[ 
	output = "" ; 
	input = "/" & modKeyString ;
	slash_count = PatternCount ( input ; "/" ) ;
	slash_include = 0
	] ; 
	slash_count > 0 ; 
		[ 
		output = output & Right ( input ; Length ( input ) - Position ( input ; "/" ; 1 ; slash_count ) + slash_include ) & "¶"; 
		input = Left ( input ; Position ( input ; "/" ; 1 ; slash_count ) - 1 ) ;
		slash_count = PatternCount ( input ; "/" ) ;
		slash_include = 1
		] ; 
	output & input
  )
)
//FOLDERS END WITH A SLASH`

**Comment by foo4thought** [comment]
running overnight, the network crashed and left 7M+ records undone when I got to the office.  those have been running since 10AM at the rate of ~500K per hour

**Comment by foo4thought** [comment]
updates completed
