### ISSUE TITLE
Export of Arkansas GUIDs that have been digitized

### ISSUE THREAD

**Issue by ekemeyer** [WGBH-MLA/mla-tickets#89]
# Details 
Hi, is it possible to get a metadata export of items from Arkansas (https://americanarchive.org/participating-orgs/1708) that have been digitized? I think they want GUID, ID, title, description (if there is one), physical format, and date, if possible!

Submitted by: Miranda
CC in communications: 
Priority: High (within the week)
URL: https://americanarchive.org/participating-orgs/1708
Slack message thread:

**Comment by foo4thought** [comment]
`mylocal:ArkansasDigitizedAAPB kevin_carter$ rows=100;start=0;while [ "$(curl -sS "https://americanarchive.org/api.json?fl=id,xml&rows=$rows&q=contributing_organizations:%22Arkansas+Educational+TV+Network+%28AR%29%22%20AND%20access_types:digitized&start=$start" | tee $start.json | jq -r '(.response.start|tonumber)<(.response.numFound|tonumber)')" == "true" ];do sleep 1;start=$[$start+$rows];done
for f in $(ls -1 *.json);do json=$(cat $f);dt=$(echo "$json" | jq -r '.response.docs|length');for dn in $(seq 0 "$dt");do guid=$(echo "$json" | jq -r --arg dn $dn '.response.docs[($dn|tonumber)].id');echo "$json" | jq -r --arg dn $dn '.response.docs[($dn|tonumber)].xml' > xml/$(echo $guid | tr '_' '-').xml;done;done
mylocal:ArkansasDigitizedAAPB kevin_carter$ ./report.sh
mylocal:ArkansasDigitizedAAPB kevin_carter$ gzip -c report.txt > arkansasDigitized1079report.tsv.gz`




[arkansasDigitized1079report.tsv.gz](https://github.com/user-attachments/files/17235595/arkansasDigitized1079report.tsv.gz)

**Comment by foo4thought** [comment]
`#!/bin/bash -l


function report {
	aapb_xml=$1 ;
	ams_id=$(echo $aapb_xml | xpath -e '//pbcoreIdentifier[@source="http://americanarchiveinventory.org"]/text()' 2>/dev/null) ;
	local_ids=$(echo $aapb_xml | xpath -e '//pbcoreIdentifier[@source = "UOI_ID" ]/@*|//pbcoreIdentifier[@source = "UOI_ID" ]/text()' 2>/dev/null | tr -s '\n' '|' | sed 's#\([^"]\)\|#\1\|\|#g;s#\|$##1') ;
	titles=$(echo $aapb_xml | xpath -e '//pbcoreTitle/@*|//pbcoreTitle/text()' 2>/dev/null | tr -s '\n' '|' | sed 's#\([^"]\)\|#\1 \|\|#g;s#\|$##1' );
	desc=$(echo $aapb_xml | xpath -e '//pbcoreDescription/@*|//pbcoreDescription/text()' 2>/dev/null | tr -s '\n' '|' | sed 's#\([^"]\)\|#\1 \|\|#g;s#\|$##1' ) ;
	dates=$(echo $aapb_xml | xpath -e '//pbcoreAssetDate/@*|//pbcoreAssetDate/text()' 2>/dev/null | tr -s '\n' '|' | sed 's#\([^"]\)\|#\1 \|\|#g;s#\|$##1' ) ;
#	rights=$(echo $aapb_xml | xpath -e '//rightsSummary/@*|//rightsSummary/text()' 2>/dev/null | tr -s '\n' '|' | sed 's#\([^"]\)\|#\1 \|\|#g;s#\|$##1' ) ;
#	access=$(echo $aapb_xml | xpath -e '//pbcoreAnnotation[@annotationType="Level of User Access"]/@*|//pbcoreAnnotation[@annotationType="Level of User Access"]/text()' 2>/dev/null | tr -s '\n' '|' | sed 's#\([^"]\)\|#\1 \|\|#g;s#\|$##1' ) ;
	formats=$(echo $aapb_xml | xpath -e '//instantiationPhysical/text()|//instantiationDigital/text()' 2>/dev/null | tr -s '\n' '|' | sed 's#\([^"]\)\|#\1 \|\|#g;s#\|$##1'  ) ;
#	inst_id=$(echo $aapb_xml | xpath -e '//instantiationIdentifier[@source="Original file name"]/text()' 2>/dev/null | tr -s '\n' '|' | sed 's#\([^"]\)\|#\1 \|\|#g;s#\|$##1'  ) ;
	inst_id=$(echo $aapb_xml | xpath -e '//pbcoreInstantiation[instantiationPhysical]/instantiationIdentifier/text()' 2>/dev/null | tr -s '\n' '|' | sed 's#\([^"]\)\|#\1 \|\|#g;s#\|$##1'  ) ;
# 	relations=$(echo $aapb_xml | xpath -e '//pbcoreRelation[pbcoreRelationType[@source="SOURCE"]]/*' 2>/dev/null | tr -s '\n' '|' | sed 's#\([^"]\)\|#\1 \|\|#g;s#\|$##1;s#\</[^\>]*\># #g;s#\<##g;s#\># = #g' ) ;
# 	coverages=$(echo $aapb_xml | xpath -e '//pbcoreCoverage/*' 2>/dev/null | tr -s '\n' '|' | sed 's#\([^"]\)\|#\1 \|\|#g;s#\|$##1;s#\</[^\>]*\># #g;s#\<##g;s#\># = #g' ) ;
	durations=$(echo $aapb_xml | xpath -e '//instantiationDuration/text()|//pbcoreInstantiation[instantiationDigital][1]/instantiationEssenceTrack/essenceTrackDuration/text()' 2>/dev/null | tr -s '\n' '|' | sed 's#\([^"]\)\|#\1 \|\|#g;s#\|$##1' );
	echo "$(echo $ams_id;echo $local_ids;echo $titles;echo $desc;echo $dates;echo $formats;echo $inst_id;echo $durations)" | paste - - - - - - - - | sed 's#|\(\t\)#\1#g' ;
}

echo "$(echo AMS_GUID;echo UOI_ID;echo AAPB_TITLE;echo DESCRIPTION;echo DATES;echo FORMATS;echo INST_ID;echo DURATIONS)" | paste  - - - - - - - - > report.txt;
for xf in $(ls -1 xml/*.xml);
do
 aapb_xml=$(cat $xf);
 report "$aapb_xml" >> report.txt;
done`

**Comment by foo4thought** [comment]
#!/bin/bash -l


function report {
	aapb_xml=$1 ;
	ams_id=$(echo $aapb_xml | xpath -e '//pbcoreIdentifier[@source="http://americanarchiveinventory.org"]/text()' 2>/dev/null) ;
	local_ids=$(echo $aapb_xml | xpath -e '//pbcoreIdentifier[@source = "UOI_ID" ]/@*|//pbcoreIdentifier[@source = "UOI_ID" ]/text()' 2>/dev/null | tr -s '\n' '|' | sed 's#\([^"]\)\|#\1\|\|#g;s#\|$##1') ;
	titles=$(echo $aapb_xml | xpath -e '//pbcoreTitle/@*|//pbcoreTitle/text()' 2>/dev/null | tr -s '\n' '|' | sed 's#\([^"]\)\|#\1 \|\|#g;s#\|$##1' );
	desc=$(echo $aapb_xml | xpath -e '//pbcoreDescription/@*|//pbcoreDescription/text()' 2>/dev/null | tr -s '\n' '|' | sed 's#\([^"]\)\|#\1 \|\|#g;s#\|$##1' ) ;
	dates=$(echo $aapb_xml | xpath -e '//pbcoreAssetDate/@*|//pbcoreAssetDate/text()' 2>/dev/null | tr -s '\n' '|' | sed 's#\([^"]\)\|#\1 \|\|#g;s#\|$##1' ) ;
#	rights=$(echo $aapb_xml | xpath -e '//rightsSummary/@*|//rightsSummary/text()' 2>/dev/null | tr -s '\n' '|' | sed 's#\([^"]\)\|#\1 \|\|#g;s#\|$##1' ) ;
#	access=$(echo $aapb_xml | xpath -e '//pbcoreAnnotation[@annotationType="Level of User Access"]/@*|//pbcoreAnnotation[@annotationType="Level of User Access"]/text()' 2>/dev/null | tr -s '\n' '|' | sed 's#\([^"]\)\|#\1 \|\|#g;s#\|$##1' ) ;
	formats=$(echo $aapb_xml | xpath -e '//instantiationPhysical/text()|//instantiationDigital/text()' 2>/dev/null | tr -s '\n' '|' | sed 's#\([^"]\)\|#\1 \|\|#g;s#\|$##1'  ) ;
#	inst_id=$(echo $aapb_xml | xpath -e '//instantiationIdentifier[@source="Original file name"]/text()' 2>/dev/null | tr -s '\n' '|' | sed 's#\([^"]\)\|#\1 \|\|#g;s#\|$##1'  ) ;
	inst_id=$(echo $aapb_xml | xpath -e '//pbcoreInstantiation[instantiationPhysical]/instantiationIdentifier/text()' 2>/dev/null | tr -s '\n' '|' | sed 's#\([^"]\)\|#\1 \|\|#g;s#\|$##1'  ) ;
# 	relations=$(echo $aapb_xml | xpath -e '//pbcoreRelation[pbcoreRelationType[@source="SOURCE"]]/*' 2>/dev/null | tr -s '\n' '|' | sed 's#\([^"]\)\|#\1 \|\|#g;s#\|$##1;s#\</[^\>]*\># #g;s#\<##g;s#\># = #g' ) ;
# 	coverages=$(echo $aapb_xml | xpath -e '//pbcoreCoverage/*' 2>/dev/null | tr -s '\n' '|' | sed 's#\([^"]\)\|#\1 \|\|#g;s#\|$##1;s#\</[^\>]*\># #g;s#\<##g;s#\># = #g' ) ;
	durations=$(echo $aapb_xml | xpath -e '//instantiationDuration/text()|//pbcoreInstantiation[instantiationDigital][1]/instantiationEssenceTrack/essenceTrackDuration/text()' 2>/dev/null | tr -s '\n' '|' | sed 's#\([^"]\)\|#\1 \|\|#g;s#\|$##1' );
	echo "$(echo $ams_id;echo $local_ids;echo $titles;echo $desc;echo $dates;echo $formats;echo $inst_id;echo $durations)" | paste - - - - - - - - | sed 's#|\(\t\)#\1#g' ;
}

echo "$(echo AMS_GUID;echo UOI_ID;echo AAPB_TITLE;echo DESCRIPTION;echo DATES;echo FORMATS;echo INST_ID;echo DURATIONS)" | paste  - - - - - - - - > report.txt;
for xf in $(ls -1 xml/*.xml);
do
 aapb_xml=$(cat $xf);
 report "$aapb_xml" >> report.txt;
done

**Comment by foo4thought** [comment]
LOL when I paste the code of `report.sh` here it volunteers to break it up and report violations and who thought that was a good idea?
