### ISSUE TITLE
add more GUIDs into ams2ool database

### ISSUE THREAD

**Issue by ekemeyer** [WGBH-MLA/mla-tickets#91]
# Details 
list of GUIDs to import into ams2ool provided to Kevin via slack

Submitted by: Miranda Villesvik
CC in communications: miranda_villesvik@wgbh.org
Priority: Medium (within this month)
URL: 
Slack message thread: https://wgbh.slack.com/archives/DLXCH9CH0/p1728051100461179

**Comment by foo4thought** [comment]
1. use file of GUIDs to run script that selects any pre-existing records ;
2. after zero matches, import GUIDs to create new records;
3. all succeeded (no format issues) so run scripts to update records with metadata from ams2 & AAPB_Enhancements
