### ISSUE TITLE
Peabody Review for Duplication: PBS, 70-89

### ISSUE THREAD

**Issue by ekemeyer** [WGBH-MLA/mla-tickets#93]
# Details 
Hi - I'm hoping I can get some help ID'ing items in an inventory we received from Peabody that are possibly either 1) already in the AAPB or 2) at the LOC. I've pulled out everything I was able to ID as already in the AAPB, as well as all WGBH programming. I've uploaded two inventories to a folder on the shared drive: the Peabody inventory UPDATED_PBS_in_Peabody_1970-1999_MKrev.xlsx) and the LOC's PBS-NET inventory (LC_NET-PBS_2in.xlsx). If you could ID possible matches, I'll then go in and do more manual checking. Let me know if you have any questions!

Submitted by: Michelle
CC in communications: 
Priority: Medium (within this month)
URL: https://drive.google.com/drive/folders/1GSmhnHrkkAfQQBdOenESGApYyVT086PD?usp=drive_link
Slack message thread:

**Comment by foo4thought** [comment]
Ugh

**Comment by foo4thought** [comment]
I'm framing up comparison logic; I plan to read each title cell in the Peabody sheet, then process each text to:

1. remove anything inside [] and ()
2. use the characters for period and comma to denote paragraphs, (e.g., it seems to translate to a line for series and another for episode)
3. search for each "title" line of the result within the column of LOC titles, ignoring case and reporting matches
4. if none found, search and report again at word level (ignoring case)

Here is a list of unique words (after filtering already described); will you remove all but ones to IGNORE, please?  i.e., I will search for all "titles" but not for words in the list to be ignored.
[words_unique.txt](https://github.com/user-attachments/files/17384926/words_unique.txt)

**Comment by foo4thought** [comment]
Results illustrated in script editor; text values to be written to file :
<img width="964" alt="Screenshot 2024-10-15 at 4 51 34 PM" src="https://github.com/user-attachments/assets/05eda52a-2ff9-43d7-a632-9e860324e347">

**Comment by foo4thought** [comment]
ran script overnight, inspected output and killed it because iterator bug.  Fixed that; re-arranged order of output columns for better VLOOKUP performance in Excel; added code to generate another file to report paired values of barcode and title word counts for use later in Excel (e.g., this a given Peabody barcode could match a given LOC title on 4/7 words, and/or filter matches by the decimal value of matches, etc)

**Comment by foo4thought** [comment]
killed script again because it was working at a problematic (slow) rate.  
exported data from Excel to TSV text and rewrite everything to work in BASH.
if this will be a regular need, I'll do it waaay more easily in FileMaker, I suspect.
data will move back into Excel after new sheets are installed.

**Comment by foo4thought** [comment]
using BASH to build a map file that will fit into Excel.  
data columns are

1. Peabody barcode 
2. Matching line number of LOC sheet
3. Number of word matches
4. Word list extending into (item 3) more columns

Progress so far:

mylocal:grep_work kevin_carter$ for n in $(seq 1 9);do grep -c '^.*\t.*\t'$n'\t' map_barcode_linenum_matchcount_wordlist.tsv | awk -F\: -v n="$n" '{print "matching " n " words: "$1" combinations.  Example:"}'; grep '^.*\t.*\t'$n'\t' map_barcode_linenum_matchcount_wordlist.tsv | head -1;echo;done
matching 1 word: 1150783 combinations.  Example:
32108051256298	1019	1	1980	

matching 2 words: 17947 combinations.  Example:
32108051256298	35875	2	Cottle	Tom	

matching 3 words: 2034 combinations.  Example:
32108051256298	35873	3	Cottle	Old	Tom	

matching 4 words: 107 combinations.  Example:
32108051661166	37297	4	Henry	Miller	No	Over	

matching 5 words: 5 combinations.  Example:
32108051661190	37380	5	Cronyn	Hume	Jessica	Over	Tandy	

matching 6 words: 1 combination.  Example:
32108051661190	37381	6	Cronyn	Hume	Jessica	No	Over	Tandy

**Comment by foo4thought** [comment]
prolly discard all the single-word matches because they're too numerous for Excel and not very helpful at all

**Comment by foo4thought** [comment]
reworked parsing of titles to delimit by [sections] and (sections) instead of simple commas and periods because commas and periods otherwise created idiotic "titles" from things like "Mr. Rogers Neighborhood" and "U.S.A."

**Comment by foo4thought** [comment]
after meeting with team, also coded queies to solr index on AAPB

**Comment by foo4thought** [comment]
lotsa parsing later, here is the XLSX compendium of data to complement original Peabody and LC sheets.  Words-level processing between Peabody and LC titles was done in FileMaker Pro; phrase-level comparisons were done within Excel using osascript API; BASH scripts were used to mediate between Peabody data and AAPB.  Code to follow.  LOL and now github is complaining my XLSX is too large.   _compressing_  NOPE!  Still too large.  Sending out of band.

**Comment by foo4thought** [comment]
Here is applescript code that generated phrase-level title matching between the two sheets "Peabody" and "LC"
Notable sections disabled/commented:
1.  revised do shell code using `sed` to parse out [sections] and (sections) and reformat into lines
2. word-level loop to write out things found
[excel_peabody_PBS_dupe_work20241015.applescript.txt](https://github.com/user-attachments/files/17618494/excel_peabody_PBS_dupe_work20241015.applescript.txt)

Word-level processing done by exporting original sheets to CSV, importing to a new FileMaker Pro database file as tables, then processed to generate additional tables for words and then harvesting word-level matches out to TSV files for use in Excel.  (details omitted here)

Harvesting of AAPB data was done using BASH, after creating the eponymous "DATA_rownum_titles_and_barcodes_UPDATED_PBS_in_Peabody_1970-1999_MKrev.tsv":
`IFS=$'\n\b\r';export r=0;for i in $(cat DATA_rownum_titles_and_barcodes_UPDATED_PBS_in_Peabody_1970-1999_MKrev.tsv );do  export line_num=$(echo $i | cut -f1);export barcode=$(echo $i | cut -f5);export titles=$(echo $i | cut -f2| sed 's#\[\([^]]*\)\]#\n#g;s#([^)]*)#\n#g;s#[,]#\n#g;s#[[:punct:]]##g;s#^ *##1;s# *$##1' | tr -s ' ' | grep '.');for title in $(echo "$titles");do r=$[$r+1]; export words_list=$(echo "$title" | sed 's#[[:punct:]]##g;s#^[[:space:]]*##1;s#[[:space:]]*$##1;s#[[:space:]]#\t#g;s#\t.\t#\t#g');export rows=100;export start=0;mkdir -p "$line_num"; if [ "$(echo $title | wc -c | awk '{print $1}')" -gt 2 ]; then until [ "$start" -ge "$(curl -sS --get --data-urlencode 'fl=id,title,xml' --data-urlencode "rows=$rows" --data-urlencode "start=$start" --data-urlencode 'q=(access_types:digitized) AND ((title:"'"$title"'") OR (("'"$(echo "$words_list" | tr -s '\t' ' ')"'"~'"$(echo "$words_list" | wc -w | awk '{print $1}')"') AND (title:'"$(echo "$words_list" | awk '{print $1}')"'*)))' https://americanarchive.org/api.json | tee "$line_num"/"$barcode"'_r'"$r"'_'"$start".json | jq -r '.response.numFound')" ];do sleep 1;start=$[$start+$rows] ;done;fi;done;done` 

subsequent processing:  summary metadata report generated by BASH code:
`IFS=$'\n\b\r';echo "$(echo spreadsheet_line_num;echo barcode;echo title_version;echo numFound;echo query)" | paste - - - - - | tee report_aapb_overview2.txt;for i in $(grep '.*_0.json'  filepaths_with_pbcoreresults.txt );do echo "$(echo $i | sed 's#/#\t#1;s#_.#\t#1;s#_.*##1' ;jq -r '.response.numFound as $nf | .responseHeader.params.q as $q | [$nf,$q] | @tsv' "$i")" | paste - - | tee -a report_aapb_overview2.txt;done`

 and

`echo "$(echo spreadsheet_line_num ;echo barcode;echo title_version;echo aapb_title;echo aapb_guid)" | paste - - - - - | tee report_ssline_barcode_vertitle_aapbtitle_guid.tsv;for i in $(cat filepaths_with_pbcoreresults.txt);do args=$(echo $i | sed 's#/#\t#1;s#_.#\t#1;s#_.*##1');spreadsheet_line_num=$(echo $args | cut -f1);barcode=$(echo $args | cut -f2);title_version=$(echo $args | cut -f3) ;jq -r --arg spreadsheet_line_num "$spreadsheet_line_num" --arg barcode "$barcode" --arg title_version "$title_version" '.response.docs[]|[($spreadsheet_line_num|tonumber),$barcode,($title_version|tonumber),.title,(.id|sub("_";"-"))]|@tsv' "$i" | tee -a report_ssline_barcode_vertitle_aapbtitle_guid.tsv ;done`

**Comment by foo4thought** [comment]
various formatting tricks done in Excel to filter and/or highlight results.  XLSX is too large for inclusion here, but see #101 for those tricks on a smaller, related data set
