### ISSUE TITLE
WYSO Records

### ISSUE THREAD

**Issue by ekemeyer** [WGBH-MLA/mla-tickets#98]
# Details 
Hi - Could I get an inventory report for all records from WYSO? And could it specify what's been digitized and what hasn't? Please include GUIDs, titles, formats, and if available, other metadata, like descriptions, dates, run times, etc. They want to use this as the basis for their inventory of materials to digitize under Mellon. Let me know if I can clarify anything -- Thank you! 

Submitted by: Michelle
CC in communications: 
Priority: Medium (within this month)
URL: https://americanarchive.org/catalog?f%5Bcontributing_organizations%5D%5B%5D=WYSO+%28OH%29&f[access_types][]=all
Slack message thread:

**Comment by foo4thought** [comment]
get metadata as JSON
`rows=100;start=0;until [ "$start" -gt "$(curl -sS 'https://americanarchive.org/api.json?fl=id,xml&rows='"$rows"'&q=%28contributing_organizations:%22WYSO%20%28OH%29%22%20AND%20access_types:all%29&start='"$start" | tee "$start.json" | jq -r '.response.numFound')" ];do sleep 1;start=$[$start+rows];done
`
`# inspect the last file created and remove if it contains 'docs[]'`

**Comment by foo4thought** [comment]
create xml files
`for jfile in $(ls -1 *.json);do docnum=0;doccount=$(jq -r '.response.docs|length' "$jfile");until [ "$docnum" -gt "$doccount"  ];do xmlguid=$(jq -r --arg docnum "$docnum" '.response.docs[($docnum|tonumber)]' "$jfile" | tee  >(jq -r '.xml' > xml/"$docnum".xml) | jq -r '.id|sub("_";"-")'  );mv xml/"$docnum".xml xml/"$xmlguid".xml;docnum=$[$docnum+1];done; done`

**Comment by ekemeyer** [comment]
sent to Michelle

**Comment by foo4thought** [comment]
well, because I already fetched fresh data and had the `xpath` in BASH script at hand, I ran it to create a more limited report file; it's easier to look at, for sure.
[ids_digitized.txt](https://github.com/user-attachments/files/17508212/ids_digitized.txt)
[wyso_report20241021_ltd.txt.gz](https://github.com/user-attachments/files/17508213/wyso_report20241021_ltd.txt.gz)

**Comment by foo4thought** [comment]
will slack files to Michell now
